/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.nlochschmidt.http4k_openfaas.example

import org.http4k.core.Request
import org.http4k.core.Response
import org.http4k.core.Status.Companion.OK
import org.http4k.server.ApacheServer
import org.http4k.server.asServer

fun main() {
    { request: Request -> Response(OK).body("Hello World") }.asServer(ApacheServer(3000)).start()
}
